### ISSUE TITLE
Is development abandoned?

### ISSUE THREAD

**Issue by Albus70007** [torial/Cobra#1]

**Comment by torial** [comment]
Yes, I was exploring a few possible improvements a few years back but stopped.  I wouldn't recommend the most recent commits for even branching (as they were in an unstable state).

**Comment by torial** [comment]
The original Cobra SVN may have more recent updates, I have not tracked it in a few years as well.

**Comment by Albus70007** [comment]
Do you know where can I find it, this is the only thing related to cobra that appeared.
Thank you

**Comment by torial** [comment]
This should get you what you need: http://cobra-language.com/trac/cobra/wiki/HowToInstallFromSource
